---
title: "Group Work Plan"
subtitle: "STT2860 S22 Project 02"
author: "Authors: Phu Tran, Nicholas Goodman, Angel Powell, Patrick Bautista"
date: "`r format(Sys.time(), '%A, %B %d, %Y @ %I:%M %p')`"
output: 
  html_document: 
    theme: yeti
    highlight: textmate
---
***

**Work Plan/Assignments**

We are planning to complete the data scientist this weekend. For part B and C, we'll split up each part and if we are having trouble on solving a problem, we will help each other and ask you for questions if needed. 

**Completion Timeline**

All of us will do the data scientist and try to complete it this weekend. Depending on everyone's schedule, we'll try to either do one part together or we split it up and have it completed on next Friday. Next weekend, we will go over the project together and see if we made any errors before submitting the project.

**Communication Plan**

We'll communicate each other through a group text every couple of days to see how is everyone's progress. We'll let you know who is submitting the project through the group forums in ASU Learn. 

***

